version: '2'

services:
  pgadmin4:
    image: fenglc/pgadmin4:1.1
    ports:
      - "5050:5050"
    links:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  data:
    driver: 'local'
